/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Material.java
 *
 * Created on 16/05/2009, 01:41:32
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.spartafw.hibernate.util.HibernateUtil;
import br.com.vebo.dados.bo.CalculoBO;
import br.com.vebo.dados.bo.MaterialBO;
import br.com.vebo.dados.bo.UtilizacaoMaterialBO;
import br.com.vebo.dados.mapeamento.Calculo;
import br.com.vebo.dados.mapeamento.Material;
import br.com.vebo.dados.mapeamento.UtilizacaoMaterial;
import br.com.vebo.dados.swing.table.CalculoTableModel;
import br.com.vebo.dados.swing.table.UtilizacaoMaterialTableModel;
import br.com.vebo.util.DoubleUtil;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class CalculoJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form Material */
    public CalculoJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        tabelaJScrolPane = new javax.swing.JScrollPane();
        calculosJTable = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtQuantidadeEssencia = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        tabelaJScrolPane1 = new javax.swing.JScrollPane();
        utilizacaoMateriaisJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarUtilizacao = new javax.swing.JButton();
        btnExcluirUtilizacao = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cálculos");
        setToolTipText("");
        setName("materialJInternalFrame"); // NOI18N

        calculosJTable.setModel(new br.com.vebo.dados.swing.table.CalculoTableModel());
        calculosJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculosJTableMouseClicked(evt);
            }
        });
        tabelaJScrolPane.setViewportView(calculosJTable);
        atualizaTabela();

        lblNome.setText("Nome");

        lblValor.setText("Quantidade Essência");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtQuantidadeEssencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.#######"))));
        txtQuantidadeEssencia.setVerifyInputWhenFocusTarget(false);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        utilizacaoMateriaisJTable.setModel(new br.com.vebo.dados.swing.table.UtilizacaoMaterialTableModel());
        utilizacaoMateriaisJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaJScrolPane1.setViewportView(utilizacaoMateriaisJTable);

        jLabel1.setText("Materiais");

        btnAdicionarUtilizacao.setText("+");
        btnAdicionarUtilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUtilizacaoActionPerformed(evt);
            }
        });

        btnExcluirUtilizacao.setText("-");
        btnExcluirUtilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUtilizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalJPanelLayout.createSequentialGroup()
                                .addComponent(lblValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidadeEssencia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalJPanelLayout.createSequentialGroup()
                                    .addComponent(lblNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(principalJPanelLayout.createSequentialGroup()
                                    .addComponent(btnLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNovo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAlterar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExcluir))
                                .addGroup(principalJPanelLayout.createSequentialGroup()
                                    .addComponent(tabelaJScrolPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAdicionarUtilizacao)
                                        .addComponent(btnExcluirUtilizacao)))))
                        .addGap(117, 117, 117))
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(458, Short.MAX_VALUE))))
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtQuantidadeEssencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAdicionarUtilizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirUtilizacao))
                    .addComponent(tabelaJScrolPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnLimpar))
                .addGap(40, 40, 40))
        );

        getContentPane().add(principalJPanel, java.awt.BorderLayout.LINE_START);

        setBounds(0, 0, 463, 429);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (validaForm()) {
            try {
                Calculo calculo = new CalculoBO().retrieve(idCalculo);
                calculo.setNome(txtNome.getText());
                calculo.setUtilizacaoEssencia(new DoubleUtil().stringParaDouble(txtQuantidadeEssencia.getText()));
                calculo.setUtilizacoes(new HashSet(((UtilizacaoMaterialTableModel)utilizacaoMateriaisJTable.getModel()).getUtilizacoes()));
                for (UtilizacaoMaterial utilizacaoMaterial : calculo.getUtilizacoes()) {
                    utilizacaoMaterial.setCalculo(calculo);
                }
                HibernateUtil.beginTransaction();
                new CalculoBO().save(calculo);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Cálculo alterado com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();
        }
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if (validaForm()) {
            Calculo novoCalculo = new Calculo();
            novoCalculo.setNome(txtNome.getText());
            novoCalculo.setUtilizacaoEssencia(new DoubleUtil().stringParaDouble(txtQuantidadeEssencia.getText()));
            novoCalculo.setUtilizacoes(new HashSet(((UtilizacaoMaterialTableModel)utilizacaoMateriaisJTable.getModel()).getUtilizacoes()));
            for (UtilizacaoMaterial utilizacaoMaterial : novoCalculo.getUtilizacoes()) {
                utilizacaoMaterial.setCalculo(novoCalculo);
            }
            try {
                HibernateUtil.beginTransaction();
                new CalculoBO().save(novoCalculo);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Cálculo inserido com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cálculo selecionado?","Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int linhaSelecionada = calculosJTable.getSelectedRow();
            try {
                Calculo calculo = new CalculoBO().retrieve((Long) calculosJTable.getValueAt(linhaSelecionada, 0));
                HibernateUtil.beginTransaction();
                new CalculoBO().delete(calculo);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Cálculo excluído com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
                limpaForm();
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
            atualizaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void calculosJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculosJTableMouseClicked
        if (evt.getClickCount() > 1) {
            try {
                Calculo calculo = new CalculoBO().retrieve((Long) calculosJTable.getValueAt(calculosJTable.getSelectedRow(), 0));
                idCalculo = calculo.getId();
                txtNome.setText(calculo.getNome());
                txtQuantidadeEssencia.setText(new DoubleUtil().doubleParaString(calculo.getUtilizacaoEssencia()));

                UtilizacaoMaterialTableModel utilizacaoMaterialTableModel = (UtilizacaoMaterialTableModel) utilizacaoMateriaisJTable.getModel();
                utilizacaoMaterialTableModel.setUtilizacoes(new ArrayList(calculo.getUtilizacoes()));
                utilizacaoMateriaisJTable.updateUI();
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_calculosJTableMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAdicionarUtilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUtilizacaoActionPerformed
        new UtilizacaoMaterialJDialog(this).setVisible(true);
    }//GEN-LAST:event_btnAdicionarUtilizacaoActionPerformed

    private void btnExcluirUtilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUtilizacaoActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o material selecionado?","Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //utilizacaoMateriaisJTable.remove(utilizacaoMateriaisJTable.getSelectedRow());
            try {

                UtilizacaoMaterialTableModel tableModel = (UtilizacaoMaterialTableModel) utilizacaoMateriaisJTable.getModel();
                UtilizacaoMaterial utilizacaoMaterial = tableModel.getUtilizacoes().remove(utilizacaoMateriaisJTable.getSelectedRow());

                new UtilizacaoMaterialBO().delete(new UtilizacaoMaterialBO().retrieve(utilizacaoMaterial.getId()));

                utilizacaoMateriaisJTable.updateUI();
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirUtilizacaoActionPerformed


    private boolean validaForm() {
        boolean retorno = true;
        StringBuffer mensagensErro = new StringBuffer();
        if (txtNome.getText().isEmpty()) {
            mensagensErro.append("O campo Nome é requerido.\n");
            retorno = false;
        }
        if (txtQuantidadeEssencia.getText().isEmpty()) {
            mensagensErro.append("O campo Quantidade é requerido.\n");
            retorno = false;
        }
        if (!retorno) {
            JOptionPane.showMessageDialog(this, mensagensErro.toString(), "Validação",  JOptionPane.ERROR_MESSAGE);
        }
        return retorno;
    }

    private void limpaForm() {
        idCalculo = 0l;
        txtNome.setText("");
        txtQuantidadeEssencia.setText("");
        atualizaTabelaUtilizacoes(new ArrayList<UtilizacaoMaterial>());
    }

    private void atualizaTabela() {

        CalculoTableModel tableModel = (CalculoTableModel) calculosJTable.getModel();
        try {
            tableModel.setCalculos((List) new CalculoBO().findAll());
        } catch (DataAccessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        calculosJTable.updateUI();
    }

    private void atualizaTabelaUtilizacoes(List<UtilizacaoMaterial> utilizacaoMateriais) {
        UtilizacaoMaterialTableModel tableModel = (UtilizacaoMaterialTableModel) utilizacaoMateriaisJTable.getModel();
        tableModel.setUtilizacoes(utilizacaoMateriais);
        utilizacaoMateriaisJTable.updateUI();
    }

    protected void adicionaUtilizacaoMaterial(UtilizacaoMaterial utilizacaoMaterial) {
        UtilizacaoMaterialTableModel tableModel = (UtilizacaoMaterialTableModel) utilizacaoMateriaisJTable.getModel();
        tableModel.getUtilizacoes().add(utilizacaoMaterial);
        utilizacaoMateriaisJTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUtilizacao;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirUtilizacao;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JTable calculosJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JScrollPane tabelaJScrolPane;
    private javax.swing.JScrollPane tabelaJScrolPane1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtQuantidadeEssencia;
    private javax.swing.JTable utilizacaoMateriaisJTable;
    // End of variables declaration//GEN-END:variables
    private Long idCalculo = 0l;
}
