/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Material.java
 *
 * Created on 16/05/2009, 01:41:32
 */

package br.com.vebo.dados.swing;

import br.com.vebo.dados.bo.ConfiguracaoBO;
import br.com.vebo.dados.mapeamento.Configuracao;
import br.com.vebo.util.DoubleUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class ConfiguracaoJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form Material */
    public ConfiguracaoJInternalFrame() {
        initComponents();
        atualizarForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        lblTaxaCusto = new javax.swing.JLabel();
        lblTaxaValorRevendedor = new javax.swing.JLabel();
        lblTaxaValorCliente = new javax.swing.JLabel();
        lblTaxaLucroRevendedor = new javax.swing.JLabel();
        txtTaxaCusto = new javax.swing.JFormattedTextField();
        txtTaxaValorRevendedor = new javax.swing.JFormattedTextField();
        txtTaxaValorCliente = new javax.swing.JFormattedTextField();
        txtTaxaLucroRevendedor = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuração");
        setName("materialJInternalFrame"); // NOI18N

        lblTaxaCusto.setText("Taxa de Cálculo do Custo");

        lblTaxaValorRevendedor.setText("Taxa do Valor do Revendedor");

        lblTaxaValorCliente.setText("Taxa do Valor do Cliente");

        lblTaxaLucroRevendedor.setText("Taxa do Lucro do Revendedor");

        txtTaxaCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0########"))));

        txtTaxaValorRevendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0########"))));

        txtTaxaValorCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0########"))));

        txtTaxaLucroRevendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0########"))));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalJPanelLayout.createSequentialGroup()
                        .addComponent(lblTaxaLucroRevendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTaxaLucroRevendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalJPanelLayout.createSequentialGroup()
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaxaValorRevendedor)
                            .addComponent(lblTaxaCusto)
                            .addComponent(lblTaxaValorCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaxaCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtTaxaValorRevendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtTaxaValorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap())
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaCusto)
                    .addComponent(txtTaxaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaValorRevendedor)
                    .addComponent(txtTaxaValorRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaValorCliente)
                    .addComponent(txtTaxaValorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaLucroRevendedor)
                    .addComponent(txtTaxaLucroRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        getContentPane().add(principalJPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 467, 292);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validaForm()) {
            try {
                Configuracao configuracao = new ConfiguracaoBO().retrieve();
                configuracao.setTaxaCusto(new DoubleUtil().stringParaDouble(txtTaxaCusto.getText()));
                configuracao.setTaxaLucroRevendedor(new DoubleUtil().stringParaDouble(txtTaxaLucroRevendedor.getText()));
                configuracao.setTaxaValorFinal(new DoubleUtil().stringParaDouble(txtTaxaValorCliente.getText()));
                configuracao.setTaxaValorRevendedor(new DoubleUtil().stringParaDouble(txtTaxaValorRevendedor.getText()));
                new ConfiguracaoBO().save(configuracao);
                JOptionPane.showMessageDialog(this, "Configuração alterada com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    private boolean validaForm() {
        boolean retorno = true;
        StringBuffer mensagensErro = new StringBuffer();
        if (txtTaxaCusto.getText().isEmpty()) {
            mensagensErro.append("O campo 'Taxa de Cálculo do Custo' é requerido.\n");
            retorno = false;
        }
        if (txtTaxaValorRevendedor.getText().isEmpty()) {
            mensagensErro.append("O campo Taxa do Valor do Revendedor' é requerido.\n");
            retorno = false;
        }
        if (txtTaxaValorCliente.getText().isEmpty()) {
            mensagensErro.append("O campo 'Taxa do Valor do Cliente' é requerido.\n");
            retorno = false;
        }
        if (txtTaxaLucroRevendedor.getText().isEmpty()) {
            mensagensErro.append("O campo Taxa do Lucro do Revendedor' é requerido.\n");
            retorno = false;
        }
        if (!retorno) {
            JOptionPane.showMessageDialog(this, mensagensErro.toString(), "Validação",  JOptionPane.ERROR_MESSAGE);
        }
        return retorno;
    }

    public void atualizarForm() {
        Configuracao configuracao = new ConfiguracaoBO().retrieve();
        txtTaxaCusto.setText(new DoubleUtil().doubleParaString(configuracao.getTaxaCusto(), "#,##0.0########"));
        txtTaxaValorRevendedor.setText(new DoubleUtil().doubleParaString(configuracao.getTaxaValorRevendedor(), "#,##0.0########"));
        txtTaxaValorCliente.setText(new DoubleUtil().doubleParaString(configuracao.getTaxaValorFinal(), "#,##0.0########"));
        txtTaxaLucroRevendedor.setText(new DoubleUtil().doubleParaString(configuracao.getTaxaLucroRevendedor(), "#,##0.0########"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblTaxaCusto;
    private javax.swing.JLabel lblTaxaLucroRevendedor;
    private javax.swing.JLabel lblTaxaValorCliente;
    private javax.swing.JLabel lblTaxaValorRevendedor;
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JFormattedTextField txtTaxaCusto;
    private javax.swing.JFormattedTextField txtTaxaLucroRevendedor;
    private javax.swing.JFormattedTextField txtTaxaValorCliente;
    private javax.swing.JFormattedTextField txtTaxaValorRevendedor;
    // End of variables declaration//GEN-END:variables
}
