/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabelaPrecoJInternalFrame.java
 *
 * Created on 17/05/2009, 22:27:08
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.vebo.dados.bo.PedidoBO;
import br.com.vebo.dados.bo.RevendedorBO;
import br.com.vebo.dados.mapeamento.Pedido;
import br.com.vebo.dados.mapeamento.Revendedor;
import br.com.vebo.dados.swing.table.PedidoTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class PedidosPorRevendedorJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form TabelaPrecoJInternalFrame */
    public PedidosPorRevendedorJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRevendedor = new javax.swing.JLabel();
        cbxRevendedor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosPorRevendedorjTable = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pedidos Por Revendedor");

        lblRevendedor.setText("Revendedor");

        cbxRevendedor.setModel(new javax.swing.DefaultComboBoxModel());
        atualizaComboBox();

        pedidosPorRevendedorjTable.setModel(new PedidoTableModel()
        );
        jScrollPane1.setViewportView(pedidosPorRevendedorjTable);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRevendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRevendedor, 0, 844, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRevendedor)
                    .addComponent(cbxRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1091)/2, (screenSize.height-701)/2, 1091, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        this.atualizaTabela((Revendedor)cbxRevendedor.getSelectedItem());
    }//GEN-LAST:event_btnAtualizarActionPerformed

    protected void atualizaComboBox() {
        try {
            if(cbxRevendedor.getItemCount() > 0){
                cbxRevendedor.removeAllItems();
            }
            
            for (Revendedor revendedor : new RevendedorBO().findAll()) {
                cbxRevendedor.addItem(revendedor);
            }
            cbxRevendedor.updateUI();
        }
        catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaTabela(Revendedor revendedor) {

        PedidoTableModel tableModel = (PedidoTableModel) pedidosPorRevendedorjTable.getModel();
        Pedido pedido = new Pedido();
        pedido.setRevendedor(revendedor);
        try {
            tableModel.setPedidos((List<Pedido>) new PedidoBO().findByFilter(pedido));
        } catch (DataAccessException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        pedidosPorRevendedorjTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox cbxRevendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRevendedor;
    private javax.swing.JTable pedidosPorRevendedorjTable;
    // End of variables declaration//GEN-END:variables


}
