/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PedidoJInternalFrame.java
 *
 * Created on 20/05/2009, 23:22:28
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.spartafw.hibernate.util.HibernateUtil;
import br.com.vebo.dados.bo.CalculoBO;
import br.com.vebo.dados.bo.PedidoBO;
import br.com.vebo.dados.bo.PerfumeBO;
import br.com.vebo.dados.bo.PrecoBO;
import br.com.vebo.dados.bo.RevendedorBO;
import br.com.vebo.dados.mapeamento.Calculo;
import br.com.vebo.dados.mapeamento.Pedido;
import br.com.vebo.dados.mapeamento.Perfume;
import br.com.vebo.dados.mapeamento.Revendedor;
import br.com.vebo.dados.swing.table.PedidoTableModel;
import br.com.vebo.util.DateUtil;
import br.com.vebo.util.DoubleUtil;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author mohfus
 */
public class PedidoJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form PedidoJInternalFrame */
    public PedidoJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRevendedorFiltro = new javax.swing.JLabel();
        cbxRevendedorFiltro = new javax.swing.JComboBox();
        btnFiltrar = new javax.swing.JButton();
        btnLimparFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosJTable = new javax.swing.JTable();
        lblRevendedor = new javax.swing.JLabel();
        cbxRevendedor = new javax.swing.JComboBox();
        lblPerfume = new javax.swing.JLabel();
        cbxPerfume = new javax.swing.JComboBox();
        lblCalculo = new javax.swing.JLabel();
        cbxCalculo = new javax.swing.JComboBox();
        btnCalcularValor = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaObservacoes = new javax.swing.JTextArea();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        lblEntrega = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JFormattedTextField();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setTitle("Pedidos");
        setToolTipText("");

        lblRevendedorFiltro.setText("Revendedor");

        cbxRevendedorFiltro.setModel(new javax.swing.DefaultComboBoxModel());

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimparFiltro.setText("Limpar Filtro");
        btnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltroActionPerformed(evt);
            }
        });

        pedidosJTable.setModel(new PedidoTableModel());
        pedidosJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pedidosJTable);
        atualizaTabela();

        lblRevendedor.setText("Revendedor");

        cbxRevendedor.setModel(new javax.swing.DefaultComboBoxModel());

        lblPerfume.setText("Perfume");

        cbxPerfume.setModel(new javax.swing.DefaultComboBoxModel());

        lblCalculo.setText("Cálculo");

        cbxCalculo.setModel(new javax.swing.DefaultComboBoxModel());

        btnCalcularValor.setText("Calcular Valor");
        btnCalcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularValorActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        lblObservacoes.setText("Observações");

        txaObservacoes.setColumns(20);
        txaObservacoes.setLineWrap(true);
        txaObservacoes.setRows(3);
        jScrollPane2.setViewportView(txaObservacoes);

        lblData.setText("Data");

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblEntrega.setText("Entrega");

        txtEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRevendedorFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxRevendedorFiltro, 0, 400, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparFiltro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRevendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRevendedor, 0, 635, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerfume)
                            .addComponent(lblCalculo)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPerfume, 0, 652, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbxCalculo, 0, 503, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularValor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblData)
                                .addGap(18, 18, 18)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEntrega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblObservacoes)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRevendedorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevendedorFiltro)
                    .addComponent(btnLimparFiltro)
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRevendedor)
                    .addComponent(cbxRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfume)
                    .addComponent(cbxPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalculo)
                    .addComponent(cbxCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntrega)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 777, 663);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if (validaForm()) {
            Pedido novoPedido = new Pedido();
            novoPedido.setCalculo((Calculo)cbxCalculo.getSelectedItem());
            novoPedido.setPerfume((Perfume)cbxPerfume.getSelectedItem());
            novoPedido.setRevendedor((Revendedor)cbxRevendedor.getSelectedItem());
            novoPedido.setEntrega(new DateUtil().stringParaDate(txtEntrega.getText()));
            novoPedido.setPedido(new DateUtil().stringParaDate(txtData.getText()));
            novoPedido.setObservacao(txaObservacoes.getText());
            novoPedido.setValor(new DoubleUtil().stringParaDouble(txtValor.getText()));
            try {
                HibernateUtil.beginTransaction();
                new PedidoBO().save(novoPedido);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Pedido inserido com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();

        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCalcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularValorActionPerformed
        txtValor.setText(new DoubleUtil().doubleParaString(new PrecoBO().calcularPreco((Perfume)cbxPerfume.getSelectedItem(), (Calculo)cbxCalculo.getSelectedItem()).getValorFinal(), "#,##0.00"));
    }//GEN-LAST:event_btnCalcularValorActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (validaForm()) {
            try {
                Pedido pedido = new PedidoBO().retrieve(idPedido);
                pedido.setCalculo((Calculo)cbxCalculo.getSelectedItem());
                pedido.setPerfume((Perfume)cbxPerfume.getSelectedItem());
                pedido.setRevendedor((Revendedor)cbxRevendedor.getSelectedItem());
                pedido.setEntrega(new DateUtil().stringParaDate(txtEntrega.getText()));
                pedido.setPedido(new DateUtil().stringParaDate(txtData.getText()));
                pedido.setObservacao(txaObservacoes.getText());
                pedido.setValor(new DoubleUtil().stringParaDouble(txtValor.getText()));

                HibernateUtil.beginTransaction();
                new PedidoBO().save(pedido);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Pedido alterado com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void pedidosJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosJTableMouseClicked
        if (evt.getClickCount() > 1) {
            int linhaSelecionada = pedidosJTable.getSelectedRow();
            try {
                Pedido pedido = new PedidoBO().retrieve((Long) pedidosJTable.getValueAt(linhaSelecionada, 0));
                idPedido = pedido.getId();
                cbxRevendedor.setSelectedItem(pedido.getRevendedor());
                cbxPerfume.setSelectedItem(pedido.getPerfume());
                cbxCalculo.setSelectedItem(pedido.getCalculo());
                txtData.setText(new DateUtil().dateParaString(pedido.getPedido()));
                txtEntrega.setText(new DateUtil().dateParaString(pedido.getEntrega()));
                txtValor.setText(new DoubleUtil().doubleParaString(pedido.getValor()));
                txaObservacoes.setText(pedido.getObservacao());
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_pedidosJTableMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o pedido selecionado?","Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int linhaSelecionada = pedidosJTable.getSelectedRow();
            try {
                Pedido pedido = new PedidoBO().retrieve((Long) pedidosJTable.getValueAt(linhaSelecionada, 0));
                HibernateUtil.beginTransaction();
                new PedidoBO().delete(pedido);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Pedido excluído com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
            atualizaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltroActionPerformed
        cbxRevendedorFiltro.setSelectedIndex(0);
        atualizaTabela();
    }//GEN-LAST:event_btnLimparFiltroActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        atualizaTabela((Revendedor)cbxRevendedorFiltro.getSelectedItem());
    }//GEN-LAST:event_btnFiltrarActionPerformed

    public void atualizaComboboxes() {
    cbxRevendedorFiltro.setModel(new DefaultComboBoxModel());
    cbxRevendedor.setModel(new DefaultComboBoxModel());
    cbxPerfume.setModel(new DefaultComboBoxModel());
    cbxCalculo.setModel(new DefaultComboBoxModel());
    try {
        for (Revendedor revendedor : new RevendedorBO().findAll()) {
            cbxRevendedorFiltro.addItem(revendedor);
            cbxRevendedor.addItem(revendedor);
        }

        for (Perfume perfume : new PerfumeBO().findAll()) {
            cbxPerfume.addItem(perfume);
        }

        for (Calculo calculo : new CalculoBO().findAll()) {
            cbxCalculo.addItem(calculo);
        }

        
    }
    catch(Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
    }
    cbxRevendedorFiltro.updateUI();
    cbxRevendedor.updateUI();
    cbxPerfume.updateUI();
    cbxCalculo.updateUI();
}

    private void atualizaTabela() {

        PedidoTableModel tableModel = (PedidoTableModel) pedidosJTable.getModel();
        try {
            tableModel.setPedidos((List) new PedidoBO().findAll());
        } catch (DataAccessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        pedidosJTable.updateUI();
    }

    private void atualizaTabela(Revendedor revendedor) {

        PedidoTableModel tableModel = (PedidoTableModel) pedidosJTable.getModel();
        try {
            Pedido filtro = new Pedido();
            filtro.setRevendedor(revendedor);
            tableModel.setPedidos((List) new PedidoBO().findByFilter(filtro));
        } catch (DataAccessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        pedidosJTable.updateUI();
    }

    private boolean validaForm() {
        boolean retorno = true;
        StringBuffer mensagensErro = new StringBuffer();

        if (txtValor.getText().isEmpty()) {
            mensagensErro.append("O campo Valor é requerido.\n");
            retorno = false;
        }
        if (txtData.getText().isEmpty()) {
            mensagensErro.append("O campo Data é requerido.\n");
            retorno = false;
        }
        if (!retorno) {
            JOptionPane.showMessageDialog(this, mensagensErro.toString(), "Validação",  JOptionPane.ERROR_MESSAGE);
        }
        return retorno;
    }

    public void limpaForm() {
        idPedido = 0l;
        cbxRevendedor.setSelectedIndex(0);
        cbxPerfume.setSelectedIndex(0);
        cbxCalculo.setSelectedIndex(0);
        txtValor.setText("");
        txtData.setText("");
        txtEntrega.setText("");
        txaObservacoes.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCalcularValor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparFiltro;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cbxCalculo;
    private javax.swing.JComboBox cbxPerfume;
    private javax.swing.JComboBox cbxRevendedor;
    private javax.swing.JComboBox cbxRevendedorFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCalculo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPerfume;
    private javax.swing.JLabel lblRevendedor;
    private javax.swing.JLabel lblRevendedorFiltro;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable pedidosJTable;
    private javax.swing.JTextArea txaObservacoes;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtEntrega;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private Long idPedido = 0l;
}
