/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Material.java
 *
 * Created on 16/05/2009, 01:41:32
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.vebo.dados.bo.PedidoBO;
import br.com.vebo.dados.swing.table.VendaPerfumeTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class PerfumesMaisVendidosJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form Material */
    public PerfumesMaisVendidosJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        tabelaJScrolPane = new javax.swing.JScrollPane();
        vendasPerfumeJTable = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Perfumes Mais Vendidos");
        setName("materialJInternalFrame"); // NOI18N

        vendasPerfumeJTable.setModel(new br.com.vebo.dados.swing.table.VendaPerfumeTableModel());
        tabelaJScrolPane.setViewportView(vendasPerfumeJTable);
        atualizaTabela();

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        getContentPane().add(principalJPanel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-593)/2, (screenSize.height-385)/2, 593, 385);
    }// </editor-fold>//GEN-END:initComponents

    public void atualizaTabela() {

        VendaPerfumeTableModel tableModel = (VendaPerfumeTableModel) vendasPerfumeJTable.getModel();
        try {
            tableModel.setVendaPerfumes((List) new PedidoBO().obterPerfumesPorVenda());
        } catch (DataAccessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        vendasPerfumeJTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JScrollPane tabelaJScrolPane;
    private javax.swing.JTable vendasPerfumeJTable;
    // End of variables declaration//GEN-END:variables

}
