/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalJFrame.java
 *
 * Created on 15/05/2009, 02:06:18
 */

package br.com.vebo.dados.swing;

/**
 *
 * @author mohfus
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /** Creates new form PrincipalJFrame */
    public PrincipalJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerFormularios = new javax.swing.JDesktopPane();
        barraMenus = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        configuracaoItemMenu = new javax.swing.JMenuItem();
        sairItemMenu = new javax.swing.JMenuItem();
        fabricacaoMenu = new javax.swing.JMenu();
        materiaisItemMenu = new javax.swing.JMenuItem();
        perfumesItemMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        calculosItemMenu = new javax.swing.JMenuItem();
        estoqueMenu = new javax.swing.JMenu();
        entradaMaterialItemMenu = new javax.swing.JMenuItem();
        retiradaMaterialItemMenu = new javax.swing.JMenuItem();
        vendaMenu = new javax.swing.JMenu();
        revendedoresItemMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        pedidosItemMenu = new javax.swing.JMenuItem();
        situacoesPedidosItemMenu = new javax.swing.JMenuItem();
        consultaMenu = new javax.swing.JMenu();
        tabelaPrecosItemMenu = new javax.swing.JMenuItem();
        pedidosRevendedorItemMenu = new javax.swing.JMenuItem();
        perfumesMaisVendidosItemMenu = new javax.swing.JMenuItem();
        relatorioMenu = new javax.swing.JMenu();
        pedidosMensaisPorRevendedorItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: VEBO ::");
        setExtendedState(MAXIMIZED_BOTH);
        setName("principalJFrame"); // NOI18N

        containerFormularios.setAutoscrolls(true);
        containerFormularios.setLayout(null);
        getContentPane().add(containerFormularios, java.awt.BorderLayout.CENTER);

        barraMenus.setName("barraMenus"); // NOI18N

        arquivoMenu.setText("Arquivo");

        configuracaoItemMenu.setText("Configuração");
        configuracaoItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracaoItemMenuActionPerformed(evt);
            }
        });
        arquivoMenu.add(configuracaoItemMenu);

        sairItemMenu.setText("Sair");
        sairItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairItemMenuActionPerformed(evt);
            }
        });
        arquivoMenu.add(sairItemMenu);

        barraMenus.add(arquivoMenu);

        fabricacaoMenu.setText("Fabricação");

        materiaisItemMenu.setText("Materiais");
        materiaisItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaisItemMenuActionPerformed(evt);
            }
        });
        fabricacaoMenu.add(materiaisItemMenu);

        perfumesItemMenu.setText("Perfumes");
        perfumesItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfumesItemMenuActionPerformed(evt);
            }
        });
        fabricacaoMenu.add(perfumesItemMenu);
        fabricacaoMenu.add(jSeparator1);

        calculosItemMenu.setText("Cálculos");
        calculosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculosItemMenuActionPerformed(evt);
            }
        });
        fabricacaoMenu.add(calculosItemMenu);

        barraMenus.add(fabricacaoMenu);

        estoqueMenu.setText("Estoque");

        entradaMaterialItemMenu.setText("Entrada de Material");
        estoqueMenu.add(entradaMaterialItemMenu);

        retiradaMaterialItemMenu.setText("Retirada de Material");
        estoqueMenu.add(retiradaMaterialItemMenu);

        barraMenus.add(estoqueMenu);

        vendaMenu.setText("Venda");

        revendedoresItemMenu.setText("Revendedores");
        revendedoresItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revendedoresItemMenuActionPerformed(evt);
            }
        });
        vendaMenu.add(revendedoresItemMenu);
        vendaMenu.add(jSeparator2);

        pedidosItemMenu.setText("Pedidos");
        pedidosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosItemMenuActionPerformed(evt);
            }
        });
        vendaMenu.add(pedidosItemMenu);

        situacoesPedidosItemMenu.setText("Situações dos Pedidos");
        situacoesPedidosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacoesPedidosItemMenuActionPerformed(evt);
            }
        });
        vendaMenu.add(situacoesPedidosItemMenu);

        barraMenus.add(vendaMenu);

        consultaMenu.setText("Consulta");

        tabelaPrecosItemMenu.setText("Tabela de Preços");
        tabelaPrecosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaPrecosItemMenuActionPerformed(evt);
            }
        });
        consultaMenu.add(tabelaPrecosItemMenu);

        pedidosRevendedorItemMenu.setText("Pedidos por Revendedor");
        pedidosRevendedorItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosRevendedorItemMenuActionPerformed(evt);
            }
        });
        consultaMenu.add(pedidosRevendedorItemMenu);

        perfumesMaisVendidosItemMenu.setText("Perfumes Mais Vendidos");
        perfumesMaisVendidosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfumesMaisVendidosItemMenuActionPerformed(evt);
            }
        });
        consultaMenu.add(perfumesMaisVendidosItemMenu);

        barraMenus.add(consultaMenu);

        relatorioMenu.setText("Relatório");

        pedidosMensaisPorRevendedorItemMenu.setText("Pedidos Mensais Por Revendedor");
        pedidosMensaisPorRevendedorItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosMensaisPorRevendedorItemMenuActionPerformed(evt);
            }
        });
        relatorioMenu.add(pedidosMensaisPorRevendedorItemMenu);

        barraMenus.add(relatorioMenu);

        setJMenuBar(barraMenus);

        setSize(new java.awt.Dimension(609, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculosItemMenuActionPerformed
        if (calculosJInternalFrame == null) {
            calculosJInternalFrame = new CalculoJInternalFrame();
            this.containerFormularios.add(calculosJInternalFrame);
        }
        calculosJInternalFrame.setVisible(true);
        calculosJInternalFrame.requestFocus();
}//GEN-LAST:event_calculosItemMenuActionPerformed

    private void sairItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairItemMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairItemMenuActionPerformed

    private void materiaisItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaisItemMenuActionPerformed
        if (materiaisJInternalFrame == null) {
            materiaisJInternalFrame = new MaterialJInternalFrame();
            this.containerFormularios.add(materiaisJInternalFrame);
        }
        materiaisJInternalFrame.setVisible(true);
        materiaisJInternalFrame.requestFocus();
}//GEN-LAST:event_materiaisItemMenuActionPerformed

    private void perfumesItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfumesItemMenuActionPerformed
        if (perfumesJInternalFrame == null) {
            perfumesJInternalFrame = new PerfumeJInternalFrame();
            this.containerFormularios.add(perfumesJInternalFrame);
        }
        perfumesJInternalFrame.setVisible(true);
        perfumesJInternalFrame.requestFocus();
    }//GEN-LAST:event_perfumesItemMenuActionPerformed

    private void tabelaPrecosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaPrecosItemMenuActionPerformed
        if (tabelaPrecoJInternalFrame == null) {
            tabelaPrecoJInternalFrame = new TabelaPrecoJInternalFrame();
            this.containerFormularios.add(tabelaPrecoJInternalFrame);
        }
        else {
            tabelaPrecoJInternalFrame.atualizaComboBox();
        }
        tabelaPrecoJInternalFrame.setVisible(true);
        tabelaPrecoJInternalFrame.requestFocus();
    }//GEN-LAST:event_tabelaPrecosItemMenuActionPerformed

    private void revendedoresItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revendedoresItemMenuActionPerformed
        if (revendedoresJInternalFrame == null) {
            revendedoresJInternalFrame = new RevendedorJInternalFrame();
            this.containerFormularios.add(revendedoresJInternalFrame);
        }
        revendedoresJInternalFrame.setVisible(true);
        revendedoresJInternalFrame.requestFocus();
    }//GEN-LAST:event_revendedoresItemMenuActionPerformed

    private void pedidosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosItemMenuActionPerformed
        
        pedidoJInternalFrame = new PedidoJInternalFrame();
        this.containerFormularios.add(pedidoJInternalFrame);
        pedidoJInternalFrame.atualizaComboboxes();
        pedidoJInternalFrame.setVisible(true);
        pedidoJInternalFrame.requestFocus();
    }//GEN-LAST:event_pedidosItemMenuActionPerformed

    private void pedidosRevendedorItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosRevendedorItemMenuActionPerformed
        if (pedidosPorRevendedorJInternalFrame == null) {
            pedidosPorRevendedorJInternalFrame = new PedidosPorRevendedorJInternalFrame();
            this.containerFormularios.add(pedidosPorRevendedorJInternalFrame);
        }
        else {
            pedidosPorRevendedorJInternalFrame.atualizaComboBox();
        }
        pedidosPorRevendedorJInternalFrame.setVisible(true);
        pedidosPorRevendedorJInternalFrame.requestFocus();
    }//GEN-LAST:event_pedidosRevendedorItemMenuActionPerformed

    private void perfumesMaisVendidosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfumesMaisVendidosItemMenuActionPerformed
        if (perfumesMaisVendidosJInternalFrame == null) {
            perfumesMaisVendidosJInternalFrame = new PerfumesMaisVendidosJInternalFrame();
            this.containerFormularios.add(perfumesMaisVendidosJInternalFrame);
        }
        else {
            perfumesMaisVendidosJInternalFrame.atualizaTabela();
        }
        perfumesMaisVendidosJInternalFrame.setVisible(true);
        perfumesMaisVendidosJInternalFrame.requestFocus();
    }//GEN-LAST:event_perfumesMaisVendidosItemMenuActionPerformed

    private void configuracaoItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracaoItemMenuActionPerformed
        if (configuracaoJInternalFrame == null) {
            configuracaoJInternalFrame = new ConfiguracaoJInternalFrame();
            this.containerFormularios.add(configuracaoJInternalFrame);
        }
        else {
            configuracaoJInternalFrame.atualizarForm();
        }
        configuracaoJInternalFrame.setVisible(true);
        configuracaoJInternalFrame.requestFocus();
    }//GEN-LAST:event_configuracaoItemMenuActionPerformed

    private void pedidosMensaisPorRevendedorItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosMensaisPorRevendedorItemMenuActionPerformed
        if (pedidosMensaisPorRevendedorJInternalFrame == null) {
            pedidosMensaisPorRevendedorJInternalFrame = new PedidosMensaisPorRevendedorJInternalFrame();
            this.containerFormularios.add(pedidosMensaisPorRevendedorJInternalFrame);
        }
        else {
            pedidosMensaisPorRevendedorJInternalFrame.atualizaComboBox();
        }
        pedidosMensaisPorRevendedorJInternalFrame.setVisible(true);
        pedidosMensaisPorRevendedorJInternalFrame.requestFocus();
}//GEN-LAST:event_pedidosMensaisPorRevendedorItemMenuActionPerformed

    private void situacoesPedidosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacoesPedidosItemMenuActionPerformed
        if (situacoesPorPedidoJInternalFrame == null) {
            situacoesPorPedidoJInternalFrame = new SituacoesPorPedidoJInternalFrame();
            this.containerFormularios.add(situacoesPorPedidoJInternalFrame);
        }

        situacoesPorPedidoJInternalFrame.setVisible(true);
        situacoesPorPedidoJInternalFrame.requestFocus();
    }//GEN-LAST:event_situacoesPedidosItemMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JMenuItem calculosItemMenu;
    private javax.swing.JMenuItem configuracaoItemMenu;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JDesktopPane containerFormularios;
    private javax.swing.JMenuItem entradaMaterialItemMenu;
    private javax.swing.JMenu estoqueMenu;
    private javax.swing.JMenu fabricacaoMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem materiaisItemMenu;
    private javax.swing.JMenuItem pedidosItemMenu;
    private javax.swing.JMenuItem pedidosMensaisPorRevendedorItemMenu;
    private javax.swing.JMenuItem pedidosRevendedorItemMenu;
    private javax.swing.JMenuItem perfumesItemMenu;
    private javax.swing.JMenuItem perfumesMaisVendidosItemMenu;
    private javax.swing.JMenu relatorioMenu;
    private javax.swing.JMenuItem retiradaMaterialItemMenu;
    private javax.swing.JMenuItem revendedoresItemMenu;
    private javax.swing.JMenuItem sairItemMenu;
    private javax.swing.JMenuItem situacoesPedidosItemMenu;
    private javax.swing.JMenuItem tabelaPrecosItemMenu;
    private javax.swing.JMenu vendaMenu;
    // End of variables declaration//GEN-END:variables
    private MaterialJInternalFrame materiaisJInternalFrame = null;
    private PerfumeJInternalFrame perfumesJInternalFrame = null;
    private CalculoJInternalFrame calculosJInternalFrame = null;
    private RevendedorJInternalFrame revendedoresJInternalFrame = null;
    private TabelaPrecoJInternalFrame tabelaPrecoJInternalFrame = null;
    private PedidoJInternalFrame pedidoJInternalFrame = null;
    private PedidosPorRevendedorJInternalFrame pedidosPorRevendedorJInternalFrame = null;
    private PerfumesMaisVendidosJInternalFrame perfumesMaisVendidosJInternalFrame = null;
    private ConfiguracaoJInternalFrame configuracaoJInternalFrame = null;
    private PedidosMensaisPorRevendedorJInternalFrame pedidosMensaisPorRevendedorJInternalFrame = null;
    private SituacoesPorPedidoJInternalFrame situacoesPorPedidoJInternalFrame = null;
    
    public static void main(String[] args) {
        new PrincipalJFrame().setVisible(true);
    }
}
