/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Material.java
 *
 * Created on 16/05/2009, 01:41:32
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.spartafw.hibernate.util.HibernateUtil;
import br.com.vebo.dados.bo.MaterialBO;
import br.com.vebo.dados.bo.RevendedorBO;
import br.com.vebo.dados.mapeamento.Material;
import br.com.vebo.dados.mapeamento.Revendedor;
import br.com.vebo.dados.swing.table.MaterialTableModel;
import br.com.vebo.dados.swing.table.RevendedorTableModel;
import br.com.vebo.util.DateUtil;
import br.com.vebo.util.DoubleUtil;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class RevendedorJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form Material */
    public RevendedorJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        tabelaJScrolPane = new javax.swing.JScrollPane();
        revendedoresJTable = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtCPF = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaEndereco = new javax.swing.JTextArea();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaObservacoes = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Revendedores");
        setName("materialJInternalFrame"); // NOI18N

        revendedoresJTable.setModel(new br.com.vebo.dados.swing.table.RevendedorTableModel());
        revendedoresJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revendedoresJTableMouseClicked(evt);
            }
        });
        tabelaJScrolPane.setViewportView(revendedoresJTable);
        atualizaTabela();

        lblNome.setText("Nome");

        lblCPF.setText("CPF");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data de Nascimento");

        txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblEmail.setText("E-Mail");

        lblTelefone.setText("Telefone");

        lblCelular.setText("Celular");

        lblEndereco.setText("Endereço");
        lblEndereco.setToolTipText("");

        txaEndereco.setColumns(20);
        txaEndereco.setLineWrap(true);
        txaEndereco.setRows(5);
        jScrollPane1.setViewportView(txaEndereco);

        lblObservacoes.setText("Observações");

        txaObservacoes.setColumns(20);
        txaObservacoes.setLineWrap(true);
        txaObservacoes.setRows(5);
        jScrollPane2.setViewportView(txaObservacoes);

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(principalJPanelLayout.createSequentialGroup()
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefone)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                            .addGroup(principalJPanelLayout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                            .addGroup(principalJPanelLayout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(lblCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblEndereco)
                    .addComponent(lblObservacoes)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalJPanelLayout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaJScrolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascimento)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular))
                .addGap(18, 18, 18)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        getContentPane().add(principalJPanel, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 714, 698);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (validaForm()) {

            try {
                Revendedor revendedor = new RevendedorBO().retrieve(id_revendedor);
                revendedor.setNome(txtNome.getText());
                revendedor.setCpf(txtCPF.getText());
                revendedor.setNascimento(new DateUtil().stringParaDate(txtDataNascimento.getText()));
                revendedor.setTelefone(txtTelefone.getText());
                revendedor.setCelular(txtCelular.getText());
                revendedor.setEmail(txtEmail.getText());
                revendedor.setEndereco(txaEndereco.getText());
                revendedor.setObservacoes(txaObservacoes.getText());
                HibernateUtil.beginTransaction();
                new RevendedorBO().save(revendedor);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Revendedor alterado com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();
            
        }
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if (validaForm()) {
            Revendedor novoRevendedor = new Revendedor();
            novoRevendedor.setNome(txtNome.getText());
            novoRevendedor.setCpf(txtCPF.getText());
            novoRevendedor.setNascimento(new DateUtil().stringParaDate(txtDataNascimento.getText()));
            novoRevendedor.setTelefone(txtTelefone.getText());
            novoRevendedor.setCelular(txtCelular.getText());
            novoRevendedor.setEmail(txtEmail.getText());
            novoRevendedor.setEndereco(txaEndereco.getText());
            novoRevendedor.setObservacoes(txaObservacoes.getText());
            try {
                HibernateUtil.beginTransaction();
                new RevendedorBO().save(novoRevendedor);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Revendedor inserido com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }

            limpaForm();
            atualizaTabela();
            
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o revendedor selecionado?","Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int linhaSelecionada = revendedoresJTable.getSelectedRow();
            try {
                Revendedor revendedor = new RevendedorBO().retrieve((Long) revendedoresJTable.getValueAt(linhaSelecionada, 0));
                HibernateUtil.beginTransaction();
                new RevendedorBO().delete(revendedor);
                HibernateUtil.commitTransaction();
                JOptionPane.showMessageDialog(this, "Revendedor excluído com sucesso", "Mensagem",  JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
            atualizaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void revendedoresJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revendedoresJTableMouseClicked
        if (evt.getClickCount() > 1) {
            try {
                Revendedor revendedor = new RevendedorBO().retrieve((Long) revendedoresJTable.getValueAt(revendedoresJTable.getSelectedRow(), 0));
                id_revendedor = revendedor.getId();
                txtNome.setText(revendedor.getNome());
                txtCPF.setText(revendedor.getCpf());
                txtDataNascimento.setText(new DateUtil().dateParaString(revendedor.getNascimento()));
                txtTelefone.setText(revendedor.getTelefone());
                txtCelular.setText(revendedor.getCelular());
                txtEmail.setText(revendedor.getEmail());
                txaEndereco.setText(revendedor.getEndereco());
                txaObservacoes.setText(revendedor.getObservacoes());
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_revendedoresJTableMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaForm();
    }//GEN-LAST:event_btnLimparActionPerformed


    private boolean validaForm() {
        boolean retorno = true;
        StringBuffer mensagensErro = new StringBuffer();
        if (txtNome.getText().isEmpty()) {
            mensagensErro.append("O campo Nome é requerido.\n");
            retorno = false;
        }
        
        if (!retorno) {
            JOptionPane.showMessageDialog(this, mensagensErro.toString(), "Validação",  JOptionPane.ERROR_MESSAGE);
        }
        return retorno;
    }

    private void limpaForm() {
        id_revendedor = 0l;
        txtNome.setText("");
        txtCPF.setText("");
        txtDataNascimento.setText("");
        txtTelefone.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        txaEndereco.setText("");
        txaObservacoes.setText("");
    }

    private void atualizaTabela() {

        RevendedorTableModel tableModel = (RevendedorTableModel) revendedoresJTable.getModel();
        try {
            tableModel.setRevendedores((List) new RevendedorBO().findAll());
        } catch (DataAccessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        revendedoresJTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JTable revendedoresJTable;
    private javax.swing.JScrollPane tabelaJScrolPane;
    private javax.swing.JTextArea txaEndereco;
    private javax.swing.JTextArea txaObservacoes;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private Long id_revendedor = 0l;
}
