/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabelaPrecoJInternalFrame.java
 *
 * Created on 17/05/2009, 22:27:08
 */

package br.com.vebo.dados.swing;

import br.com.spartafw.exception.DataAccessException;
import br.com.vebo.dados.bo.PedidoBO;
import br.com.vebo.dados.bo.RevendedorBO;
import br.com.vebo.dados.mapeamento.Pedido;
import br.com.vebo.dados.mapeamento.Revendedor;
import br.com.vebo.dados.mapeamento.SituacaoPagamentoPedidoEnum;
import br.com.vebo.dados.mapeamento.SituacaoPedidoEnum;
import br.com.vebo.dados.swing.table.PedidoTableModel;
import br.com.vebo.dados.swing.table.SituacaoPedidoTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class SituacoesPorPedidoJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form TabelaPrecoJInternalFrame */
    public SituacoesPorPedidoJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRevendedor = new javax.swing.JLabel();
        cbxSituacaoPedido = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        situacoesPedidosjTable = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        lblRevendedor1 = new javax.swing.JLabel();
        cbxSituacaoPagamento = new javax.swing.JComboBox();
        btnAlterarSituacaoPedido = new javax.swing.JButton();
        btnAlterarSituacaoPagamento = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Situações do Pedido");

        lblRevendedor.setText("Situação do Pedido");

        cbxSituacaoPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODAS", "FEITO", "AGUARDANDO_ESSENCIA", "ENTREGUE" }));

        situacoesPedidosjTable.setModel(new SituacaoPedidoTableModel()
        );
        jScrollPane1.setViewportView(situacoesPedidosjTable);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblRevendedor1.setText("Situação do Pagamento");

        cbxSituacaoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODAS", "PENDENTE", "PAGO" }));

        btnAlterarSituacaoPedido.setText("Alterar Situação do Pedido");
        btnAlterarSituacaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSituacaoPedidoActionPerformed(evt);
            }
        });

        btnAlterarSituacaoPagamento.setText("Alterar Situação do Pagamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRevendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSituacaoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRevendedor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(btnAlterarSituacaoPedido)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarSituacaoPagamento)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRevendedor)
                    .addComponent(cbxSituacaoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevendedor1)
                    .addComponent(cbxSituacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarSituacaoPagamento)
                    .addComponent(btnAlterarSituacaoPedido))
                .addContainerGap())
        );

        setBounds(0, 0, 985, 606);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        this.atualizaTabela();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnAlterarSituacaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSituacaoPedidoActionPerformed
        int linhaSelecionada = situacoesPedidosjTable.getSelectedRow();
        new AlterarSituacaoPedidoJDialog(this, (Long) situacoesPedidosjTable.getValueAt(linhaSelecionada, 0));
    }//GEN-LAST:event_btnAlterarSituacaoPedidoActionPerformed

    private Pedido obterPedidoFiltro() {
        Pedido pedido = new Pedido();
        if (!cbxSituacaoPedido.getSelectedItem().equals("TODAS")) {
            pedido.setSituacaoPedido(SituacaoPedidoEnum.valueOf((String)cbxSituacaoPedido.getSelectedItem()));
        }
        else {
            pedido.setSituacaoPedido(null);
        }
        if (!cbxSituacaoPagamento.getSelectedItem().equals("TODAS")) {
            pedido.setSituacaoPagamentoPedido(SituacaoPagamentoPedidoEnum.valueOf((String)cbxSituacaoPagamento.getSelectedItem()));
        }
        else {
            pedido.setSituacaoPagamentoPedido(null);
        }
        return pedido;
    }

    protected void atualizaTabela() {

        SituacaoPedidoTableModel tableModel = (SituacaoPedidoTableModel) situacoesPedidosjTable.getModel();

        try {
            tableModel.setPedidos((List<Pedido>) new PedidoBO().findByFilter(obterPedidoFiltro()));
        } catch (DataAccessException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        situacoesPedidosjTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSituacaoPagamento;
    private javax.swing.JButton btnAlterarSituacaoPedido;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox cbxSituacaoPagamento;
    private javax.swing.JComboBox cbxSituacaoPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRevendedor;
    private javax.swing.JLabel lblRevendedor1;
    private javax.swing.JTable situacoesPedidosjTable;
    // End of variables declaration//GEN-END:variables


}
