/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabelaPrecoJInternalFrame.java
 *
 * Created on 17/05/2009, 22:27:08
 */

package br.com.vebo.dados.swing;

import br.com.vebo.dados.bo.CalculoBO;
import br.com.vebo.dados.bo.PerfumeBO;
import br.com.vebo.dados.bo.PrecoBO;
import br.com.vebo.dados.dto.PrecoDTO;
import br.com.vebo.dados.mapeamento.Calculo;
import br.com.vebo.dados.mapeamento.Perfume;
import br.com.vebo.dados.mapeamento.UtilizacaoMaterial;
import br.com.vebo.dados.swing.table.TabelaPrecoTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mohfus
 */
public class TabelaPrecoJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form TabelaPrecoJInternalFrame */
    public TabelaPrecoJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCalculo = new javax.swing.JLabel();
        cbxCalculo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrecojTable = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tabela de Preço");

        lblCalculo.setText("Cálculo");
        lblCalculo.setToolTipText("");

        cbxCalculo.setModel(new javax.swing.DefaultComboBoxModel());
        atualizaComboBox();

        tabelaPrecojTable.setModel(new TabelaPrecoTableModel()
        );
        jScrollPane1.setViewportView(tabelaPrecojTable);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCalculo, 0, 565, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalculo)
                    .addComponent(cbxCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        setBounds(0, 0, 786, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        this.atualizaTabela(calculaPrecos((Calculo)cbxCalculo.getSelectedItem()));
    }//GEN-LAST:event_btnAtualizarActionPerformed


    private List<PrecoDTO> calculaPrecos(Calculo calculo) {
        List<PrecoDTO> retorno = new ArrayList<PrecoDTO>();
        try {
            for (Perfume perfume : new PerfumeBO().findAll()) {
                PrecoDTO precoDTO = new PrecoBO().calcularPreco(perfume, calculo);
                retorno.add(precoDTO);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        return retorno;
    }

    protected void atualizaComboBox() {
        try {
            if(cbxCalculo.getItemCount() > 0){
                cbxCalculo.removeAllItems();
            }
            
            for (Calculo calculo : new CalculoBO().findAll()) {
                cbxCalculo.addItem(calculo);
            }
            cbxCalculo.updateUI();
        }
        catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaTabela(List<PrecoDTO> precos) {

        TabelaPrecoTableModel tableModel = (TabelaPrecoTableModel) tabelaPrecojTable.getModel();
        tableModel.setPrecos(precos);
        tabelaPrecojTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox cbxCalculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalculo;
    private javax.swing.JTable tabelaPrecojTable;
    // End of variables declaration//GEN-END:variables


}
